### PR TITLE
Add 8 lab

### PR DESCRIPTION
**Pull request by mikitasolo**

### CODE REVIEW

**Comment by Ivanko5417** [comment]
Please, add tests

**Comment by mikitasolo** [comment]
@Ivanko5417 added tests

**Comment by Ivanko5417** [comment]
Please, add documentation

**Comment by mikitasolo** [comment]
@Ivanko5417 added documentation

**Comment by Ivanko5417** [comment]
Please, add bugs

**Comment by mikitasolo** [comment]
@Ivanko5417 added bugs

**Comment by Ivanko5417** [comment]
Unfortunatelly this PR cannot be merged, our testers team found a bug:
image
Bugs must be fixed

**Comment by mikitasolo** [comment]
@Ivanko5417 all bugs were fixed!

**Comment by Ivanko5417** [comment]
Everything is fine!

**Pull request merged**
